### ISSUE TITLE
Ongoing project evaluation

### ISSUE THREAD

**Issue by sjkoelle** [diyadas/say-no-to-projects#3]
Give yourself one or 2 weeks to make minimum viable project.  Then send to a collaborator with fresh eyes.  Collaborators lose interest quickly with lack of visible progress, so it is important to get them onboard with something tangible.  If you can't create something tangible enough to get someone interested within 10 days, then maybe the project is not a good idea.

**Comment by diyadas** [comment]
Thank you - added!
