### ISSUE TITLE
Service Pt 1

### ISSUE THREAD

**Issue by sastoudt** [diyadas/say-no-to-projects#6]
**Is this suggestion for evaluating new or ongoing commitments?**

new commitment - deciding whether or not to get involved in a particular realm of service

**Please write your suggestion as a brief question. For example: "Do I wish to contribute?"**

Does the work require a body or does it require my particular experience, point of view, and/or set of skills?

**Comment by diyadas** [comment]
Thanks so much! Sorry I fell a bit behind in incorporating this. I've retitled the committee column to "service" as I feel that's more general. Thanks for the inspiration.
