### ISSUE TITLE
Make evaluations when being tired

### ISSUE THREAD

**Issue by bsipocz** [diyadas/say-no-to-projects#8]
**Is this suggestion for evaluating new or ongoing commitments?**
both

**Please write your suggestion as a brief question. For example: "Do I wish to contribute?"**
Make evaluations when tired. It's easier to say yes to things when being energetic and optimistic. E.g. after night observing it's more realistic to evaluate how tired one would be on a 3 day meeting that requires 30hr+ of travel to get there and back.

**Comment by diyadas** [comment]
Added, thank you!
