### ISSUE TITLE
How many work days will travelling to/from this conference cost me?

### ISSUE THREAD

**Issue by bsipocz** [diyadas/say-no-to-projects#9]
**Is this suggestion for evaluating new or ongoing commitments?**
Events

**Please write your suggestion as a brief question. For example: "Do I wish to contribute?"**
"How many work days will travelling to/from this conference cost me?"

This is very much relevant for side kick projects that are not part of the primary day job.

**Comment by diyadas** [comment]
also added! thanks again.
